#!/bin/sh
INSTANCE_ID="$2"
wget http://deploy.copezc.com:7001/srv/deploy/boot/$INSTANCE_ID -O $INSTANCE_ID
cd `dirname $0`/..

ROOT_PATH="/home/appadmin/haproxy"
BASE_DIR="`pwd`"
ARGV="$1"

start(){
    echo "start haproxy service"
    /usr/sbin/haproxy -f $ROOT_PATH/$INSTANCE_ID
}

stop(){
   killall haproxy
   echo "stop haproxy service"
}

case $ARGV in
start)
 	start
	ERROR=$?
   	;;
stop)
    stop
    ERROR=$?
    ;;
restart)
    stop
   	start
    ERROR=$?
     ;;
*)
     echo "hactl [start|restart|stop]"
esac

exit $ERROR
                                                                                                                                                                     